#######################################################################################################################
# Upsun demo project configuration
#######################################################################################################################
# Application configuration.
applications:
    # Python App
    upsun-demo:
        type: "python:3.12"

        hooks:
            build: |
                set -eux
                poetry install
                
        web:
            commands:
                start: "poetry run app"
            upstream:
                socket_family: tcp
            locations:
                /:
                    passthru: true

        relationships:
          api:
            service: "backend"
            endpoint: "http"

# #add_service_start
# ######################################################################################################################
# # Step 3: Add a service. Uncomment this section.
# ######################################################################################################################
#         relationships:
#             redis_session: 
#                 service: "redis_service"
#                 endpoint: "redis"

# services:
#     redis_service:
#         type: "redis:7.0"
# ######################################################################################################################
# #add_service_end
    
# Routes configuration.
routes:
    "https://{default}/":
        id: default-route
        type: upstream
        primary: true
        upstream: "upsun-demo:http"

    "https://www.{default}":
        id: www-redirect
        type: redirect
        to: "https://{default}/"

