#######################################################################################################################
# Upsun demo project configuration
#######################################################################################################################
# Application configuration.
applications:
    # Python App
    upsun-demo:
        type: "python:3.12"

        dependencies:
            python3:
                poetry: '*'

        variables:
            env:
                POETRY_VIRTUALENVS_IN_PROJECT: true
                POETRY_VIRTUALENVS_CREATE: true

        hooks:
            build: |
                set -eux
                poetry install --without dev
                poetry run tailwindcss -i ./upsun_demo_app/static/css/tailwind.css -o ./upsun_demo_app/static/css/main.css
        web:
            commands:
                start: "poetry run app-serve"

            locations:
                /:
                    passthru: true

# #add_service_start
# ######################################################################################################################
# # Step 3: Add a service. Uncomment this section.
# ######################################################################################################################
#         relationships:
#             redis_session: 
#                 service: "redis_service"
#                 endpoint: "redis"

# services:
#     redis_service:
#         type: "redis:7.0"
# ######################################################################################################################
# #add_service_end
    
# Routes configuration.
routes:
    "https://{default}/":
        id: default-route
        type: upstream
        primary: true
        upstream: "upsun-demo:http"

    "https://www.{default}":
        id: www-redirect
        type: redirect
        to: "https://{default}/"

